"""Initial migration.

Revision ID: d1ed382bb055
Revises: 
Create Date: 2022-02-02 13:39:08.107765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd1ed382bb055'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.Column('size', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('traits', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('aon_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actor')
    # ### end Alembic commands ###
